using UnityEngine;

public class WaypointFollower : MonoBehaviour
{
    [SerializeField] private GameObject[] waypoints; //建路近c的到M
    private int currentWaypointIndex = 0; //索引

    [SerializeField] private float speed = 2f; //速度

    void Update()
    {
        if (Vector2.Distance(waypoints[currentWaypointIndex].transform.position, transform.position) < .1f) //zy是否到_第一c
        {
            currentWaypointIndex++; //切Q到下一c
            if (currentWaypointIndex >= waypoints.Length) //如果到_路近c的末尾
            {
                currentWaypointIndex = 0; //切Q到起c
            }
        }
        transform.position = Vector2.MoveTowards(transform.position, waypoints[currentWaypointIndex].transform.position, Time.deltaTime * speed);
        //用movetowards方法移
        //Time.deltaTime * speed 主要用于 确保移动速率不受帧率影响
    }

}
